# Generated by Django 3.1.4 on 2021-01-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdescription',
            name='repo_url',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
