# Generated by Django 3.1.4 on 2021-02-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_stats', '0007_auto_20210205_0311'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('panel_type', models.CharField(choices=[('piechart', 'Pie-chart of languages used'), ('barchart', 'Bar-chart of language sizes')], max_length=127)),
            ],
        ),
        migrations.RemoveField(
            model_name='projectdescription',
            name='panel_type',
        ),
        migrations.RemoveField(
            model_name='projectdescription',
            name='title',
        ),
    ]
