# Generated by Django 3.1.4 on 2021-02-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_stats', '0008_auto_20210205_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdescription',
            name='project_name',
            field=models.CharField(max_length=30),
        ),
    ]
